### PR TITLE
Prevent shell expansion for env variables containing secrets

### PR DESCRIPTION
**Pull request by vadimklimov**
If the values of configuration parameters contain references to environment variables, and these values would reveal secrets after shell expansion, then shell expansion should be prevented to avoid potential security risks.

The following configuration parameters are considered to contain secrets:
- tmn-userid
- tmn-password
- oauth-clientid
- oauth-clientsecret

### CODE REVIEW

**Comment by ambravo** [comment]
The Oauth 2.0 RFC specifies that the `client_id` is not a secret. Some Oauth grants do not even require a `client_secret` (but those are interactive flows)

I see value in keeping it available to identify the client initiating the request.

https://datatracker.ietf.org/doc/html/rfc6749#section-2.2

**Comment by engswee** [comment]
Thanks @ambravo for sharing that, it's really good to know. Good to also know that you are still lurking around in the shadows and popping up every now and then to drop a nugget of wisdom! 😉

**Comment by vadimklimov** [comment]
@ambravo thank you for your comment, that's a very good point. I tend to think that a client ID (same as a username in basic authentication) is not truly a secret. Following this train of thought, from the list of configuration parameters provided above, only `tmn-password` and `oauth-clientsecret` shall be considered as those containing secrets.

On the other hand, do we want to consider client ID and username as sensitive (not secret but still sensitive) information and ensure their values don't get used in the broader range of configuration parameters - for example, in those used to define directories that are used by FlashPipe? Or do we want to relax that requirement and prevent shell expansion only for the very few parameters that contain truly secret data in their values?

**Comment by engswee** [comment]
Yes, they are not secrets, but they are still sensitive. Especially userid which gets can get printed out in the logs if they are expanded, which is not great IMHO.
@vadimklimov - let's keep those four, but reword to use sensitive instead of secret.

**Pull request merged**
