### PR TITLE
Tenant Snapshot, bug smashing, minor improvements

### PR DESCRIPTION
**Pull request by ambravo**
# Pull request 20210725-1 - Flashpipe 2.2.2

To the best of my knowledge, this pull request should not break anything. A new branch is advised.

#### Problem:
Some standard SAP Packages have an indicator (Field: Mode) with the "READ_ONLY" value. Unfortunately, it is not possible to download these packages with the current API.
#### Proposed and Implemented Solution: 
Added a new method to the class [IntegrationPackage](https://github.com/ambravo/flashpipe/blob/ab12d5042e582ce33a67f58c8d9e8c78514ecbe5/src/main/groovy/io/github/engswee/flashpipe/cpi/api/IntegrationPackage.groovy#L111) that verifies if the package has been catalogued as read-only. Then, this method is utilised in the class [DownloadIntegrationPackageContent](https://github.com/ambravo/flashpipe/blob/ab12d5042e582ce33a67f58c8d9e8c78514ecbe5/src/main/groovy/io/github/engswee/flashpipe/cpi/exec/DownloadIntegrationPackageContent.groovy#L53).

#### Problem:
The feature I have been working on requires subdirectories when using the working directory. Unfortunately, the current implementation does not support subdirectories.
#### Proposed and Implemented Solution: 
java.io.File.mkdirs() instead of java.io.File.mkdir() in [DownloadIntegrationPackageContent](https://github.com/ambravo/flashpipe/blob/ab12d5042e582ce33a67f58c8d9e8c78514ecbe5/src/main/groovy/io/github/engswee/flashpipe/cpi/exec/DownloadIntegrationPackageContent.groovy#L62)

#### Rationale:
To implement one new feature, I planned to directly call DownloadIntegrationPackageContent.execute() from a new Class. There is a problem with this; the method "execute()" instead of accepting parameters uses environment variables. I find it cumbersome to set a new JVM instance to call the method with new environment variables (or... am I missing something? like a magic "System.setEnv()" in groovy?)
#### Proposed and Implemented Alternative: 
Instead of jumping to modify the class (invasive IMO), I modified the bash script that downloads packages in a non-invasive way. The script now accepts arguments that override the environment variables. [sync_to_git_repository.sh](https://github.com/ambravo/flashpipe/blob/ab12d5042e582ce33a67f58c8d9e8c78514ecbe5/src/main/docker/script/sync_to_git_repository.sh#L53)
#### Rationale:
To implement one new feature, instead of creating a new commit per package, I wanted to have one commit for the whole process. So this new argument executes the download/unzipping/comparison process without commit the files.
#### Proposed and Implemented Alternative: 
The new argument :) [sync_to_git_repository.sh](https://github.com/ambravo/flashpipe/blob/ab12d5042e582ce33a67f58c8d9e8c78514ecbe5/src/main/docker/script/sync_to_git_repository.sh#L146)
#### Rationale:
To implement one new feature, I needed the list of packages of the tenant. I wanted to use a POJO approach (similar to the OData client generated by SAP's SDK), but I didn't particularly appreciate introducing new dependencies for a small method. Hence, this method returns a list of packages with all the information provided by the standard API call.
#### Proposed and Implemented Alternative: 
The new method :) [IntegrationPackage.getPackagesList()](https://github.com/ambravo/flashpipe/blob/ab12d5042e582ce33a67f58c8d9e8c78514ecbe5/src/main/groovy/io/github/engswee/flashpipe/cpi/api/IntegrationPackage.groovy#L124)

#### Driver:
As part of my CI/CD activities, I wanted a constant process (or on-demand) that triggers a snapshot of a development tenant. Also, I needed some protection from junior developers in a large integration team (without getting into details).

#### Implemented feature
This new feature is composed of a new class ([GetTenantSnapshot](https://github.com/ambravo/flashpipe/blob/ab12d5042e582ce33a67f58c8d9e8c78514ecbe5/src/main/groovy/io/github/engswee/flashpipe/cpi/exec/GetTenantSnapshot.groovy#L14)) that calls the scrip sync_to_git_repository.sh for all the tenant packages and a new script that calls the new class, and the script [snapshot_to_git_repository.sh](https://github.com/ambravo/flashpipe/blob/ab12d5042e582ce33a67f58c8d9e8c78514ecbe5/src/main/docker/script/snapshot_to_git_repository.sh#L1) that is called by the pipeline's workflow.

#### Roadmap
- Save credential artefacts (without the passwords)
- Save the list of certificates, but without the content. The list might include the certificate fingerprint.
- Save the list of Cloud Connectors available and the resources they expose.
- Save the list of created roles. (Management and Runtime)

#### TO-DOs
TODOs are marked with the tag "-TODO-" in the code.
- Time zone in the default commit message.
- Add support for git branches.

#### Known problems
~~Artefacts protected with Access Policies require the user or oAuth client that runs the pipeline to have that access policy role attached. Besides attaching that role, a possible workaround could be to ignore the artefacts. Notwithstanding, this problem also affects the currently implemented features.~~
Edit: I just found the following role, It would have to be attached to the user/client that calls the API:
Trial Home  me@amba is Trial  Overview - SAP BTP Cockpit 2021-07-27 at 1 35 59 pm

#### Sample workflow
The following configuration file is a sample workflow that leverages the new feature. (Replace the XXXXXs with your values)

```
name: Tenant Snapshot
on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Target Git directory (relative from repository root)'
        required: true
      draft:
        description: 'Draft handling (optional) - SKIP (default value if empty), ADD, ERROR'
        required: false        
      message:
        description: 'Commit message (optional)'
        required: false        
jobs:
  take_snapshot:
    runs-on: ubuntu-latest
    container:
      image: xxxxxxx/flashpipe:xxxxx
    env:
      HOST_TMN: XXXXXXXXXX
      HOST_OAUTH: dummy.authentication.eu10.hana.ondemand.com
      BASIC_USERID: ${{ secrets.DEV_USER_ID }}
      BASIC_PASSWORD: ${{ secrets.DEV_PASSWORD }}     
    steps:
    - uses: actions/checkout@v2
    - name: 'Set GIT_SRC_DIR for sync_to_git_repository.sh'
      run: |
        echo "GIT_SRC_DIR=$GITHUB_WORKSPACE/${{ github.event.inputs.directory }}" >> $GITHUB_ENV
    - name: 'Take a snapshot'
      run: /usr/bin/snapshot_to_git_repository.sh
      shell: bash
      env:
        DRAFT_HANDLING: ${{ github.event.inputs.draft }}
        COMMIT_MESSAGE: ${{ github.event.inputs.message }}
        PACKAGE_ID: "/"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
```

#### Tests

All the tests were done using a currently private image (abravoayala/flashpipe:latest) and a Neo tenant (EU2) with circa 80 packages and +400 iflows. Under these parameters, the executions took about an average of 12  minutes to execute.

Sync repo from tenant · amba-cpi-tests-fp@c730abc 2021-07-25 at 10 42 59 pm

## Outro

Other suggestions and questions will be added to the issues of the official Flashpipe repo for a wider discussion.

Topics:
- Tag management in docker hub
- Integration packages details as object's attributes
- Logger with a debug option
- Branch management
- Workflows examples in the main repo
- Downloading elements protected with access Policies
- (Parameter) Force Push - Rebase options
- (Parameter) Git Ignore / Configuration

## Authors

- Ariel Bravo-Ayala [@ambravo](https://github.com/ambravo) // https://amba.is

  Signed-off-by: Ariel Bravo-Ayala <me@amba.is>

### CODE REVIEW

**Comment by ambravo** [comment]
Now I am curious about your testing pipeline. Are the same tests that the ones in the GitHub repo? Those tests pass on my environment.

flashpipe — -zsh — 155×64 2021-07-25 at 11 06 38 pm

**Comment by engswee** [comment]
Hi @ambravo, thanks for submitting the PR, I appreciate such comprehensive details that was provided. 👍🏻

Today is the first day that I'm back from vacation, so there's quite a bit of backlog of work to go through. Please be patient and I'll get back to you.

**Comment by ambravo** [comment]
Thanks @engswee! I just edited the PR (Known problems section) as I found a role that would sort that issue. Is this something to include [here?
Trial Home   me@amba is Trial   Overview - SAP BTP Cockpit 2021-07-27 at 1 35 59 pm
](https://engswee.github.io/flashpipe/oauth_client.html)

**Comment by engswee** [comment]
Hi @ambravo,

I finally got around to digesting this, and oh my, this is quite a bit to digest! 😂 However, this idea for tenant snapshot is cool, and I am thrilled that you are willing to collaborate and contribute to this repository. 👍🏻

Following are my responses, and I hope I didn't miss anything out.
- Package read only check - wasn't aware so thanks for highlighting and adding this
- Recursive directory creation on working directory - no problem here
- getPackagesList method - no problem here

For the part about arguments instead env var, I'd really prefer to retain it as env var. The real issue here is that you want to reuse the logic in DownloadIntegrationPackageContent, and this is really a fault on my end - I was lazy and should have made it modular. I like to keep the flow of calls to be 
_Unix script -> exec class (those in io.github.engswee.flashpipe.cpi.exec) -> other internal classes_

and therefore avoid script calling Java calling script.

I can refactor out the common parts from DownloadIntegrationPackageContent into a common class, which can then be called from GetTenantSnapshot. What do you think?

I think this new feature will need some further work, so this PR can be merged into a new branch, and we continue working on that before it finally makes it into main and a release.

Some other thoughts:
- what's builder.sh that you added to .gitignore
- your effort here forced me to pen down my thoughts what should go into the [contributing guidelines](https://github.com/engswee/flashpipe/blob/main/CONTRIBUTING.md) - thanks for that!
- testing pipeline will not work for PR because it runs integration tests against a tenant, and the credentials are secrets that are not accessible when the build is triggered from PR


Thanks again for your proactive contribution to this repository!

**Comment by ambravo** [comment]
Hi @engswee,
Thanks for the reply. I totally agree; I should have to split this into multiple commits. The problem was I started the feature, but the bugs came across during testing, so I lost track of the order of changes and ended up working with a shallow repo.  It would have been ideal as you could have cherry-picked the right ones. I saw this coming hence the message at the beginning requesting a new branch 👍 

I believe refactoring DownloadIntegrationPackageContent makes sense. However, I am not really a fan of env variables to pass parameters. This is purely my view, but I believe that env vars are... env vars... as in environment. This means that things such as credentials/hostnames/base paths are good candidates for env vars, but then IDs/ filters/options are not. This is how many CLIs work (and these classes can perfectly be wrapped into one!)

While calling scripts from a Class is not ideal, I tried to be unintrusive with the Downloader class, and the updated script is backwards compatible. Then I had "time to market" constrain, so I just got into the zone. This can definitely be improved, and happy to refactor it when the approach is agreed upon.

The builder.sh is a raw one-liner that builds the maven project, update the image, pushes it to the hub and triggers the workflow (It doesn't delete dangling images 🙈):
```#!/bin/bash
mvn package && docker build -t abravoayala/flashpipe:latest -f src/main/docker/Dockerfile . && docker push abravoayala/flashpipe:latest  && gh workflow run tenant-snapshot.yml -f directory=/my_dir -f draft=ADD```

How are you testing this locally? I ended up creating a container and "bashing" into it. (I'm not proficient in java!) 
Bests

**Comment by engswee** [comment]
Hi @ambravo 

I understand where you are coming from about CLIs and env vars. The initial approach for scripts started off with using arguments, and was only switched to env vars in version 2.0.0 onwards. The reasons behind that were:
- as new parameters were added, the command line became longer and harder to read in the YAML (see example [here](https://github.com/engswee/flashpipe-demo/blob/1d26cee0dc07f068ebf0665a4581011f7ebe1da3/azure-pipelines.yml#L69-L78) from version 1.0.2)
- handling mandatory and optional parameters increased the complexity of the script - and I wanted to gradually reduce the script complexity because it is harder to debug/test Bash compared to Java/Groovy (and you did ask about local testing on this too!)
- the usage of the scripts are mainly in the context of a CI/CD pipeline and not traditional CLIs. Using env vars makes the YAML more readable with the `env` section where the parameters are listed vertically as compared to horizontally (like in the above example)

Totally can relate to the 'time to market' constrain - the big chunk of code in DownloadIntegrationPackageContent was also a product of that 🙈! But it's never too late to refactor, especially now that there is a motive for me to do so 😉 I'll merge this PR tomorrow into a new branch, and will let you know once refactoring is done on my end.

About testing locally, as I'm using IntelliJ IDEA, I have run configurations that enables me to execute the Groovy classes and easily pass env vars into them.
image

I can also test shell scripts from the IDE, but per my reason above, I'm trying to keep the script complexity low and avoid needing to test the logic there. Once in a while, I do create a container and bash into it, but only when I can't reproduce the issue through other "simpler" testing manners.

I also have run configurations to do some of the stuff you have on your `builder.sh`.

Not too familiar with VS Code so not sure if you can have similar stuff like these run configurations.

Let me know if you need further help on setting up for local testing.

**Comment by ambravo** [comment]
Thanks for the clarification. Just to be 100% sure, are those the only reasons? I am asking because:

1. Your example:

```yaml
- bash: /usr/bin/update_designtime_artifact.sh --manifest_file="$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/QA/MANIFEST.MF" --param_file="$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/QA/parameters.prop" /tmp $DEV_HOST_TMN $DEV_CPI_USER $DEV_CPI_PW GroovyXMLTransformation_QA "Groovy XML Transformation QA" FlashPipeDemoQA "FlashPipe Demo QA" "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
```
 Can be transformed into this:
```yaml
- bash: >-
  /usr/bin/update_designtime_artifact.sh 
  --manifest_file="$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/QA/MANIFEST.MF" 
  --param_file="$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/QA/parameters.prop" 
  /tmp 
  $DEV_HOST_TMN $DEV_CPI_USER 
  $DEV_CPI_PW 
  GroovyXMLTransformation_QA 
  "Groovy XML Transformation QA" 
  FlashPipeDemoQA 
  "FlashPipe Demo QA" 
  "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
```
using YAML folding (the ">" creates a fold and the "-" removes the line breaks creating a single line). 

2. Validate mandatory field should be straightforward using [this](https://github.com/ambravo/flashpipe/blob/af3ccf3304f9bfb4b3b69dd7c9ca5868ad7d2840/src/main/docker/script/sync_to_git_repository.sh#L58), in conjunction with [this](https://github.com/ambravo/flashpipe/blob/af3ccf3304f9bfb4b3b69dd7c9ca5868ad7d2840/src/main/docker/script/sync_to_git_repository.sh#L27).

Now, if it is personal taste... then there is nothing wrong with personal preferences! Yet I really believe the method would be restricted using purely "env vars". It feels wrong, but take my "feelings" with a pinch of salt as I am not a Java/Groovy star (I've indeed not written a book 😉). I will support you either way. 👍

Regarding VS Code, I use it for NodeJs primarily, but it is a great all in one. Notably, I am using VS Code as I am testing Co-Pilot (Which is great and scary!).

**Comment by engswee** [comment]
Thanks for sharing about YAML folding - I wasn't aware of that, so it's good to know.

It's hard to say if these were the only reasons and whether I'm 100% sure. I was trying to recreate something similar with out-of-the-box pipeline steps where you can see the parameter name and value pair, like the example below.

image

I guess it's possible to do that with YAML folding as well, but at this point it would take more effort to reengineer that and update all the documentation 😰, plus it then is no longer backwards compatible - which introduces a hassle to whoever is using it at the moment.

If it makes it easier, let's call it my "personal preference" 😉

Regarding Co-Pilot, I was tempted to give it a try, but at the end I feel it might end up being a distraction for me, with so much concrete stuff that I have on my plate to deliver right now. I'm not ready to switch to VS Code as I've tried it before and I feel for Java/Groovy development, the experience on IntelliJ IDEA is superior. The choice of IDE is **very** subjective - I understand that it is a great all-in-one (and configurable) and many swear by it, but for me, I'm the type that prefers the best tool for the job at hand.

**Comment by ambravo** [comment]
Totally understand. As I said, you have my support either way. (It also give me the leverage of a future "I told you so" 🤣 if things go south)

Related to this:

> it then is no longer backwards compatible - which introduces a hassle to whoever is using it at the moment.

It will not, as you have been posting static tags to your images. This is something I wanted to mention. I am unsure if you are using semantic versioning (If is documented... I missed it). If so, you can have an extra tag handling the latest or the latest for a given minor version.

**Comment by engswee** [comment]
> (It also give me the leverage of a future "I told you so" 🤣 if things go south)

No problem, you officially have my permission to do so 😂

Yes, the tags... I saw you mention it in the Outro section. You know what... I just realised I missed out mentioning SemVer in the documentation - I really thought I did, so now that's another TODO on my plate. 😔

Two points on tags
- what I meant was hassle for those using it at the moment, to migrate to the next version - no longer as simple as bumping the image version
- I intentionally did not include a `latest` tag. Using `latest` might be beneficial during development phase, but is not recommended for productive environments. If the `latest` accidentally had a critical bug, or breaking change, someone's productive pipeline would suddenly be brought down, when it was working perfectly the day before. It's quite similar when using Maven for Java/Groovy developments - static version numbers for dependencies are defined in the POM and not a dynamic `latest` version

As always, happy to hear your thoughts - a lively discourse is always enlightening 😉

**Comment by ambravo** [comment]
You have raised two good points and the great thing is that they do not conflict with the creation of  _**extra**_ tag(s) on a new release. Hence, for production, you should use the specific release tag, full stop. For non-prod environments and following semver,  stable tags are a good thing at least for patches (IMO). 

For example, assuming you are releasing version 1.2.3, my suggestion for tags would be:
```
:1.2.3
:1.2.X-latest
```
...and who knows:
```
:latest
:future
:dev
:naugthy
```

**Comment by engswee** [comment]
Hi @ambravo 

I just released version [2.3.0](https://github.com/engswee/flashpipe/releases/tag/2.3.0) which includes the tenant snapshot functionality you contributed.

The refactoring of GetTenantSnapshot to use the new class wasn't that complex, so I just went ahead and did it on my end.

Your point on extra rolling tags was also a great idea - the baseline image used for FlashPipe's docker image also has the same concept, so starting from this new version, you will have these rolling tags to use.

Thanks again for your superb contribution. I really appreciate it and the lively discussion we had. I know it won't be the end, as this is just the start and I'll be seeing more from you based on the roadmap you described 😉👍🏻

**Pull request merged**
